name: Publish Packages
on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/
          scope: "@rothzerg"

      - name: Install dependencies
        run: |
          yarn
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna exec npm run test

      - name: "Version and publish"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm publish --access public
