name: Publish Packages
on:
  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@rothzerg"

      - name: Configure CI Git User
        run: |
          git config --global user.email 'hello@emrerothzerg.com'
          git config --global user.name 'GitHub Actions'

      - name: Install dependencies
        run: |
          yarn
          npx lerna bootstrap

      - name: Run tests
        run: npx lerna exec npm run test

      - name: "Version and publish"
        run: lerna publish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
